#!/usr/bin/env bun

// speed up `blowgun --version` etc
async function checkForVersion() {
  if (["v", "version", "-v", "--v", "-version", "--version"].includes(process.argv[2])) {
    const contents = await Bun.file(__dirname + "/package.json").text()

    var package = JSON.parse(contents)
    console.log(package.version)
    process.exit(0)
  }
}

async function main() {
  await checkForVersion()

  require("./cli/run.js").run(process.argv)
}

main()
